"""init

Revision ID: aa443a1da333
Revises: 
Create Date: 2026-03-27 17:14:06.433004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'aa443a1da333'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_name'), ['name'], unique=False)
        batch_op.create_index('ix_activities_path', ['path'], unique=False)

    op.create_table('buildings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.create_index('idx_buildings_coordinates', ['coordinates'], unique=False, postgresql_using='gist')
        batch_op.create_index('ix_buildings_address', ['address'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)

    op.create_table('organization_activities',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'activity_id')
    )
    with op.batch_alter_table('organization_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_activities_activity_id'), ['activity_id'], unique=False)

    op.create_table('organization_phones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_phones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_phones_phone_number'), ['phone_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_phones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_phones_phone_number'))

    op.drop_table('organization_phones')
    with op.batch_alter_table('organization_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_activities_activity_id'))

    op.drop_table('organization_activities')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_building_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_index('ix_buildings_address')
        batch_op.drop_index('idx_buildings_coordinates', postgresql_using='gist')

    op.drop_table('buildings')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activities_path')
        batch_op.drop_index(batch_op.f('ix_activities_name'))

    op.drop_table('activities')
    # ### end Alembic commands ###
